naftiko: "1.0.0-alpha2"

info:
  label: "Flipdish API - Apps — WhiteLabelConfig"
  description: >-
    WhiteLabelConfig operations on the Flipdish Open API v1.0 (10 operations).
    Lead operation: Flipdish Health Check. Self-contained Naftiko capability covering one Flipdish business surface.
  tags:
    - Flipdish
    - Online Ordering
    - White Label Config
  created: "2026-06-02"
  modified: "2026-06-02"

binds:
  - namespace: env
    keys:
      FLIPDISH_TOKEN: FLIPDISH_TOKEN

capability:

  consumes:
    - type: http
      namespace: "apps-white-label-config"
      baseUri: "https://api.flipdish.co"
      description: "Flipdish API - Apps — WhiteLabelConfig business capability. Self-contained, no shared references."
      authentication:
        type: bearer
        token: "{{env.FLIPDISH_TOKEN}}"
      resources:
        - name: "whitelabelconfig-health"
          path: "/api/v1.0/whitelabelconfig/health"
          operations:
            - name: "HealthCheck"
              method: GET
              description: "Flipdish Health Check"
              outputRawFormat: json
              outputParameters:
                - name: result
                  type: object
                  value: "$."
        - name: "whitelabelconfig-id-wlid"
          path: "/api/v1.0/whitelabelconfig/id/{wlid}"
          operations:
            - name: "GetWhiteLabelConfig"
              method: GET
              description: "Flipdish Get White Label Config"
              inputParameters:
                - name: "wlid"
                  in: path
                  type: integer
                  required: true
                  description: "The wlid path parameter."
              outputRawFormat: json
              outputParameters:
                - name: result
                  type: object
                  value: "$."
        - name: "whitelabelconfig-name-app-id"
          path: "/api/v1.0/whitelabelconfig/name/{appId}"
          operations:
            - name: "GetWhiteLabelConfigByAppNameId"
              method: GET
              description: "Flipdish Get White Label Config by App Name Id"
              inputParameters:
                - name: "appId"
                  in: path
                  type: string
                  required: true
                  description: "The app id path parameter."
              outputRawFormat: json
              outputParameters:
                - name: result
                  type: object
                  value: "$."
        - name: "whitelabelconfig-app-id-general"
          path: "/api/v1.0/whitelabelconfig/{appId}/general"
          operations:
            - name: "GetAppGeneralConfig"
              method: GET
              description: "Flipdish Get App General Config"
              inputParameters:
                - name: "appId"
                  in: path
                  type: string
                  required: true
                  description: "The app id path parameter."
              outputRawFormat: json
              outputParameters:
                - name: result
                  type: object
                  value: "$."
        - name: "whitelabelconfig-app-id-general"
          path: "/api/v1.0/whitelabelconfig/{appId}/general"
          operations:
            - name: "UpdateAppGeneralConfig"
              method: POST
              description: "Flipdish Update App General Config"
              inputParameters:
                - name: "appId"
                  in: path
                  type: string
                  required: true
                  description: "The app id path parameter."
                - name: body
                  in: body
                  type: object
                  required: true
                  description: "Request body payload."
              outputRawFormat: json
              outputParameters:
                - name: result
                  type: object
                  value: "$."
        - name: "whitelabelconfig-app-id-appstore"
          path: "/api/v1.0/whitelabelconfig/{appId}/appstore"
          operations:
            - name: "GetAppStoreConfig"
              method: GET
              description: "Flipdish Get App Store Config"
              inputParameters:
                - name: "appId"
                  in: path
                  type: string
                  required: true
                  description: "The app id path parameter."
              outputRawFormat: json
              outputParameters:
                - name: result
                  type: object
                  value: "$."
        - name: "whitelabelconfig-app-id-appstore"
          path: "/api/v1.0/whitelabelconfig/{appId}/appstore"
          operations:
            - name: "UpdateAppStoreConfig"
              method: POST
              description: "Flipdish Update App Store Config"
              inputParameters:
                - name: "appId"
                  in: path
                  type: string
                  required: true
                  description: "The app id path parameter."
                - name: body
                  in: body
                  type: object
                  required: true
                  description: "Request body payload."
              outputRawFormat: json
              outputParameters:
                - name: result
                  type: object
                  value: "$."
        - name: "whitelabelconfig-app-id-playstore"
          path: "/api/v1.0/whitelabelconfig/{appId}/playstore"
          operations:
            - name: "GetPlayStoreConfig"
              method: GET
              description: "Flipdish Get Play Store Config"
              inputParameters:
                - name: "appId"
                  in: path
                  type: string
                  required: true
                  description: "The app id path parameter."
              outputRawFormat: json
              outputParameters:
                - name: result
                  type: object
                  value: "$."
        - name: "whitelabelconfig-app-id-playstore"
          path: "/api/v1.0/whitelabelconfig/{appId}/playstore"
          operations:
            - name: "UpdatePlayStoreConfig"
              method: POST
              description: "Flipdish Update Play Store Config"
              inputParameters:
                - name: "appId"
                  in: path
                  type: string
                  required: true
                  description: "The app id path parameter."
                - name: body
                  in: body
                  type: object
                  required: true
                  description: "Request body payload."
              outputRawFormat: json
              outputParameters:
                - name: result
                  type: object
                  value: "$."
        - name: "whitelabelconfig-app-id-app-store-icon"
          path: "/api/v1.0/whitelabelconfig/{appId}/app-store-icon"
          operations:
            - name: "UploadAppStoreIcon"
              method: POST
              description: "Flipdish Upload App Store Icon"
              inputParameters:
                - name: "appId"
                  in: path
                  type: string
                  required: true
                  description: "The app id path parameter."
                - name: body
                  in: body
                  type: object
                  required: true
                  description: "Request body payload."
              outputRawFormat: json
              outputParameters:
                - name: result
                  type: object
                  value: "$."

  exposes:
    - type: rest
      namespace: "apps-white-label-config-rest"
      port: 8080
      description: "REST adapter for Flipdish API - Apps — WhiteLabelConfig."
      resources:
        - path: "/v1/whitelabelconfig/health"
          name: "whitelabelconfig-health"
          description: "REST surface for HealthCheck."
          operations:
            - method: GET
              name: "HealthCheck"
              description: "Flipdish Health Check"
              call: "apps-white-label-config.HealthCheck"
              outputParameters:
                - type: object
                  mapping: "$."
        - path: "/v1/whitelabelconfig/id/{wlid}"
          name: "whitelabelconfig-id-wlid"
          description: "REST surface for GetWhiteLabelConfig."
          operations:
            - method: GET
              name: "GetWhiteLabelConfig"
              description: "Flipdish Get White Label Config"
              call: "apps-white-label-config.GetWhiteLabelConfig"
              with:
                "wlid": "rest.wlid"
              outputParameters:
                - type: object
                  mapping: "$."
        - path: "/v1/whitelabelconfig/name/{app-id}"
          name: "whitelabelconfig-name-app-id"
          description: "REST surface for GetWhiteLabelConfigByAppNameId."
          operations:
            - method: GET
              name: "GetWhiteLabelConfigByAppNameId"
              description: "Flipdish Get White Label Config by App Name Id"
              call: "apps-white-label-config.GetWhiteLabelConfigByAppNameId"
              with:
                "appId": "rest.appId"
              outputParameters:
                - type: object
                  mapping: "$."
        - path: "/v1/whitelabelconfig/{app-id}/general"
          name: "whitelabelconfig-app-id-general"
          description: "REST surface for GetAppGeneralConfig."
          operations:
            - method: GET
              name: "GetAppGeneralConfig"
              description: "Flipdish Get App General Config"
              call: "apps-white-label-config.GetAppGeneralConfig"
              with:
                "appId": "rest.appId"
              outputParameters:
                - type: object
                  mapping: "$."
        - path: "/v1/whitelabelconfig/{app-id}/general"
          name: "whitelabelconfig-app-id-general"
          description: "REST surface for UpdateAppGeneralConfig."
          operations:
            - method: POST
              name: "UpdateAppGeneralConfig"
              description: "Flipdish Update App General Config"
              call: "apps-white-label-config.UpdateAppGeneralConfig"
              with:
                "appId": "rest.appId"
                body: "rest.body"
              outputParameters:
                - type: object
                  mapping: "$."
        - path: "/v1/whitelabelconfig/{app-id}/appstore"
          name: "whitelabelconfig-app-id-appstore"
          description: "REST surface for GetAppStoreConfig."
          operations:
            - method: GET
              name: "GetAppStoreConfig"
              description: "Flipdish Get App Store Config"
              call: "apps-white-label-config.GetAppStoreConfig"
              with:
                "appId": "rest.appId"
              outputParameters:
                - type: object
                  mapping: "$."
        - path: "/v1/whitelabelconfig/{app-id}/appstore"
          name: "whitelabelconfig-app-id-appstore"
          description: "REST surface for UpdateAppStoreConfig."
          operations:
            - method: POST
              name: "UpdateAppStoreConfig"
              description: "Flipdish Update App Store Config"
              call: "apps-white-label-config.UpdateAppStoreConfig"
              with:
                "appId": "rest.appId"
                body: "rest.body"
              outputParameters:
                - type: object
                  mapping: "$."
        - path: "/v1/whitelabelconfig/{app-id}/playstore"
          name: "whitelabelconfig-app-id-playstore"
          description: "REST surface for GetPlayStoreConfig."
          operations:
            - method: GET
              name: "GetPlayStoreConfig"
              description: "Flipdish Get Play Store Config"
              call: "apps-white-label-config.GetPlayStoreConfig"
              with:
                "appId": "rest.appId"
              outputParameters:
                - type: object
                  mapping: "$."
        - path: "/v1/whitelabelconfig/{app-id}/playstore"
          name: "whitelabelconfig-app-id-playstore"
          description: "REST surface for UpdatePlayStoreConfig."
          operations:
            - method: POST
              name: "UpdatePlayStoreConfig"
              description: "Flipdish Update Play Store Config"
              call: "apps-white-label-config.UpdatePlayStoreConfig"
              with:
                "appId": "rest.appId"
                body: "rest.body"
              outputParameters:
                - type: object
                  mapping: "$."
        - path: "/v1/whitelabelconfig/{app-id}/app-store-icon"
          name: "whitelabelconfig-app-id-app-store-icon"
          description: "REST surface for UploadAppStoreIcon."
          operations:
            - method: POST
              name: "UploadAppStoreIcon"
              description: "Flipdish Upload App Store Icon"
              call: "apps-white-label-config.UploadAppStoreIcon"
              with:
                "appId": "rest.appId"
                body: "rest.body"
              outputParameters:
                - type: object
                  mapping: "$."

    - type: mcp
      namespace: "apps-white-label-config-mcp"
      port: 9090
      transport: http
      description: "MCP adapter for Flipdish API - Apps — WhiteLabelConfig."
      tools:
        - name: "health-check"
          description: "Flipdish Health Check"
          hints:
            readOnly: true
            destructive: false
            idempotent: true
          call: "apps-white-label-config.HealthCheck"
          outputParameters:
            - type: object
              mapping: "$."
        - name: "get-white-label-config"
          description: "Flipdish Get White Label Config"
          hints:
            readOnly: true
            destructive: false
            idempotent: true
          call: "apps-white-label-config.GetWhiteLabelConfig"
          with:
            "wlid": "tools.wlid"
          outputParameters:
            - type: object
              mapping: "$."
        - name: "get-white-label-config-app"
          description: "Flipdish Get White Label Config by App Name Id"
          hints:
            readOnly: true
            destructive: false
            idempotent: true
          call: "apps-white-label-config.GetWhiteLabelConfigByAppNameId"
          with:
            "appId": "tools.appId"
          outputParameters:
            - type: object
              mapping: "$."
        - name: "get-app-general-config"
          description: "Flipdish Get App General Config"
          hints:
            readOnly: true
            destructive: false
            idempotent: true
          call: "apps-white-label-config.GetAppGeneralConfig"
          with:
            "appId": "tools.appId"
          outputParameters:
            - type: object
              mapping: "$."
        - name: "update-app-general-config"
          description: "Flipdish Update App General Config"
          hints:
            readOnly: false
            destructive: false
            idempotent: false
          call: "apps-white-label-config.UpdateAppGeneralConfig"
          with:
            "appId": "tools.appId"
            body: "tools.body"
          outputParameters:
            - type: object
              mapping: "$."
        - name: "get-app-store-config"
          description: "Flipdish Get App Store Config"
          hints:
            readOnly: true
            destructive: false
            idempotent: true
          call: "apps-white-label-config.GetAppStoreConfig"
          with:
            "appId": "tools.appId"
          outputParameters:
            - type: object
              mapping: "$."
        - name: "update-app-store-config"
          description: "Flipdish Update App Store Config"
          hints:
            readOnly: false
            destructive: false
            idempotent: false
          call: "apps-white-label-config.UpdateAppStoreConfig"
          with:
            "appId": "tools.appId"
            body: "tools.body"
          outputParameters:
            - type: object
              mapping: "$."
        - name: "get-play-store-config"
          description: "Flipdish Get Play Store Config"
          hints:
            readOnly: true
            destructive: false
            idempotent: true
          call: "apps-white-label-config.GetPlayStoreConfig"
          with:
            "appId": "tools.appId"
          outputParameters:
            - type: object
              mapping: "$."
        - name: "update-play-store-config"
          description: "Flipdish Update Play Store Config"
          hints:
            readOnly: false
            destructive: false
            idempotent: false
          call: "apps-white-label-config.UpdatePlayStoreConfig"
          with:
            "appId": "tools.appId"
            body: "tools.body"
          outputParameters:
            - type: object
              mapping: "$."
        - name: "upload-app-store-icon"
          description: "Flipdish Upload App Store Icon"
          hints:
            readOnly: false
            destructive: false
            idempotent: false
          call: "apps-white-label-config.UploadAppStoreIcon"
          with:
            "appId": "tools.appId"
            body: "tools.body"
          outputParameters:
            - type: object
              mapping: "$."
